const express = require('express');
const PDFDocument = require('pdfkit');
const WasteRequest = require('../models/WasteRequest');
const User = require('../models/User');
const Plant = require('../models/Plant');
const { auth } = require('../middleware/auth');

const router = express.Router();

// GET /api/certificate/:requestId – Download recycling certificate PDF
router.get('/:requestId', auth, async (req, res) => {
    try {
        const request = await WasteRequest.findById(req.params.requestId)
            .populate('generatorId', 'name email')
            .populate('plantId', 'name address');

        if (!request) return res.status(404).json({ error: 'Request not found' });
        if (request.status !== 'QC Completed') {
            return res.status(400).json({ error: 'QC not completed yet' });
        }

        const doc = new PDFDocument({ size: 'A4', margin: 50 });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=certificate-${request._id}.pdf`);
        doc.pipe(res);

        // Header
        doc.fontSize(24).font('Helvetica-Bold').fillColor('#1B5E20')
            .text('WASTE-TRACE', { align: 'center' });
        doc.fontSize(14).font('Helvetica').fillColor('#616161')
            .text('Recycling Certificate', { align: 'center' });
        doc.moveDown(2);

        // Divider
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#1B5E20');
        doc.moveDown();

        // Certificate body
        doc.fontSize(12).fillColor('#333');
        doc.font('Helvetica-Bold').text('Certificate ID: ', { continued: true });
        doc.font('Helvetica').text(request._id.toString());
        doc.moveDown(0.5);

        doc.font('Helvetica-Bold').text('Date: ', { continued: true });
        doc.font('Helvetica').text(new Date(request.updatedAt).toLocaleDateString('en-IN'));
        doc.moveDown(0.5);

        doc.font('Helvetica-Bold').text('Generator: ', { continued: true });
        doc.font('Helvetica').text(request.generatorId?.name || 'N/A');
        doc.moveDown(0.5);

        doc.font('Helvetica-Bold').text('Recycling Plant: ', { continued: true });
        doc.font('Helvetica').text(request.plantId?.name || 'N/A');
        doc.moveDown(0.5);

        doc.font('Helvetica-Bold').text('Waste Type: ', { continued: true });
        doc.font('Helvetica').text(request.wasteType);
        doc.moveDown(0.5);

        doc.font('Helvetica-Bold').text('Quantity: ', { continued: true });
        doc.font('Helvetica').text(`${request.actualWeight || request.quantity} tons`);
        doc.moveDown(0.5);

        doc.font('Helvetica-Bold').text('Contamination: ', { continued: true });
        doc.font('Helvetica').text(`${request.contamination}%`);
        doc.moveDown(0.5);

        doc.font('Helvetica-Bold').text('Green Credits Issued: ', { continued: true });
        doc.font('Helvetica').text(`${request.creditIssued} GC`);
        doc.moveDown(2);

        // Credit breakdown
        doc.font('Helvetica-Bold').fillColor('#1B5E20').text('Credit Calculation Breakdown:');
        doc.font('Helvetica').fillColor('#333');
        doc.text(`Q (Quantity) = ${request.actualWeight || request.quantity} tons`);
        doc.text(`P (Purity Factor) = ${request.purityFactor}`);
        doc.text(`R (Recovery Efficiency) = ${request.recoveryEfficiency}`);
        doc.text(`L (Logistics Multiplier) = ${request.logisticsMultiplier}`);
        doc.text(`GC = Q × P × R × L = ${request.creditIssued}`);
        doc.moveDown(2);

        // Footer
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#1B5E20');
        doc.moveDown();
        doc.fontSize(10).fillColor('#999')
            .text('This certificate is digitally generated by the Waste-Trace platform.', { align: 'center' });
        doc.text('Promoting circular economy through responsible C&D waste management.', { align: 'center' });

        doc.end();
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

module.exports = router;
